//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_22._103k_NefedovaPZ5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.Zakaz1 = new HashSet<Zakaz>();
        }
    
        public int ID_client { get; set; }
        public string Familiya { get; set; }
        public string Name { get; set; }
        public string phonenumber { get; set; }
        public string emale { get; set; }
        public int ID_zakaz { get; set; }
        public int ID_vhod { get; set; }
    
        public virtual Vhod Vhod { get; set; }
        public virtual Zakaz Zakaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz1 { get; set; }
    }
}
