//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_22._103k_NefedovaPZ5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class infotovari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infotovari()
        {
            this.SpisokPhotoTovarov = new HashSet<SpisokPhotoTovarov>();
        }
    
        public int ID_infotovara { get; set; }
        public string opisanie { get; set; }
        public string size { get; set; }
        public int ID_diler { get; set; }
    
        public virtual Diler Diler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpisokPhotoTovarov> SpisokPhotoTovarov { get; set; }
    }
}
