//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_22._103k_NefedovaPZ5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infouslugi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Infouslugi()
        {
            this.SpisokPhotoUslug = new HashSet<SpisokPhotoUslug>();
        }
    
        public int ID_infouslugi { get; set; }
        public string opisanie { get; set; }
        public int ID_material { get; set; }
        public int ID_sotrudnik { get; set; }
        public string vremya_vuypolneniya { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpisokPhotoUslug> SpisokPhotoUslug { get; set; }
    }
}
