//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_22._103k_NefedovaPZ5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhotocentreEntities1 : DbContext
    {
        public PhotocentreEntities1()
            : base("name=PhotocentreEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<Diler> Diler { get; set; }
        public virtual DbSet<infotovari> infotovari { get; set; }
        public virtual DbSet<Infouslugi> Infouslugi { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Ostatki_fototovarov> Ostatki_fototovarov { get; set; }
        public virtual DbSet<Raspisanie> Raspisanie { get; set; }
        public virtual DbSet<Sostoyanie_zakaza> Sostoyanie_zakaza { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<SpisokPhotoTovarov> SpisokPhotoTovarov { get; set; }
        public virtual DbSet<SpisokPhotoUslug> SpisokPhotoUslug { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vhod> Vhod { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
    }
}
