//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_22._103k_NefedovaPZ5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ostatki_fototovarov
    {
        public int ID_ostatki { get; set; }
        public int ID_fototovar { get; set; }
        public string kolichestvo_na_sklade { get; set; }
    
        public virtual SpisokPhotoTovarov SpisokPhotoTovarov { get; set; }
    }
}
