//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_22._103k_NefedovaPZ5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpisokPhotoTovarov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpisokPhotoTovarov()
        {
            this.Ostatki_fototovarov = new HashSet<Ostatki_fototovarov>();
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int ID_phototovara { get; set; }
        public string name_tovara { get; set; }
        public int ID_infotovara { get; set; }
        public decimal cena { get; set; }
        public string kolichestvo_na_sklade { get; set; }
    
        public virtual infotovari infotovari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ostatki_fototovarov> Ostatki_fototovarov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
