//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_22._103k_NefedovaPZ5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpisokPhotoUslug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpisokPhotoUslug()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int ID_photouslug { get; set; }
        public string name_uslugi { get; set; }
        public int ID_infouslugi { get; set; }
        public decimal cena { get; set; }
    
        public virtual Infouslugi Infouslugi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
