//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_22._103k_NefedovaPZ5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.client = new HashSet<client>();
        }
    
        public int ID_zakaz { get; set; }
        public int ID_sostoyanie_zakaza { get; set; }
        public int ID_client { get; set; }
        public Nullable<int> ID_fototovar { get; set; }
        public Nullable<int> ID_fotousluga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client> client { get; set; }
        public virtual client client1 { get; set; }
        public virtual Sostoyanie_zakaza Sostoyanie_zakaza { get; set; }
        public virtual SpisokPhotoTovarov SpisokPhotoTovarov { get; set; }
        public virtual SpisokPhotoUslug SpisokPhotoUslug { get; set; }
    }
}
